import type { CanvaResumeTemplate } from "@/types/template";

// How to add more Canva templates:
// 1. Design the resume as A4 in Canva.
// 2. Export the finished design as a PNG and put it in public/templates for the gallery thumbnail.
// 3. IMPORTANT: create a clean background copy without baked-in personal data/photo/text.
//    If the background contains old text, the app cannot erase it because it is part of the image.
// 4. Add a template object to this registry.
// 5. Adjust x/y/width/height values until the overlay fits.
// 6. Use showLabel: true for editable section titles. Users can rename/hide these in the editor.
//
// Coordinates are percentage-based from 0 to 100. The live preview uses the same values,
// and the PDF renderer converts them to A4 points.

export const canvaResumeTemplates: CanvaResumeTemplate[] = [
  {
    id: "my-cv",
    name: "My CV Visual Template",
    description:
      "Editable one-page visual CV inspired by your Canva design. The old Canva file is only a thumbnail; the exported PDF uses a clean background plus editable real text, links, QR, and image.",
    thumbnail: "/templates/My-CV.png",
    backgroundImage: "/templates/my-cv-clean-bg.png",
    pageSize: "A4",
    coordinateSystem: {
      unit: "percent",
      width: 100,
      height: 100,
    },
    fields: [
      {
        id: "fullName",
        label: "Full name",
        type: "text",
        required: true,
        x: 6.2,
        y: 2.2,
        width: 87,
        height: 5.3,
        fontSize: 24,
        fontWeight: "bold",
        color: "#2d333a",
        align: "center",
        maxChars: 38,
        maxLines: 1,
        aiMode: "fit-template-space",
        sourceKey: "fullName",
      },
      {
        id: "profileImage",
        label: "Profile image",
        type: "image",
        required: false,
        x: 8.5,
        y: 9.8,
        width: 25.5,
        height: 20,
        fontSize: 10,
        color: "#111827",
        sourceKey: "profileImage",
        placeholderImage: "/profile-placeholder.png",
      },
      {
        id: "contactTitle",
        label: "Contact me",
        type: "text",
        required: false,
        x: 5.7,
        y: 31.7,
        width: 28,
        height: 3,
        fontSize: 13,
        fontWeight: "bold",
        color: "#0b2239",
        maxChars: 18,
        maxLines: 1,
        sourceKey: "contactTitle",
      },
      {
        id: "phone",
        label: "Phone",
        type: "phone",
        required: true,
        x: 6.2,
        y: 35.0,
        width: 29,
        height: 2.4,
        fontSize: 12,
        fontWeight: "bold",
        color: "#111827",
        maxChars: 24,
        maxLines: 1,
        sourceKey: "phone",
        linkType: "phone",
      },
      {
        id: "email",
        label: "Email",
        type: "email",
        required: true,
        x: 6.2,
        y: 38.2,
        width: 31,
        height: 2.3,
        fontSize: 9.2,
        fontWeight: "semibold",
        color: "#0b2239",
        maxChars: 40,
        maxLines: 1,
        sourceKey: "email",
        linkType: "email",
      },
      {
        id: "education",
        label: "EDUCATION",
        type: "education-list",
        required: true,
        x: 5.5,
        y: 42.2,
        width: 31.5,
        height: 16.5,
        fontSize: 7.8,
        color: "#1f2937",
        maxChars: 420,
        maxLines: 10,
        sourceKey: "education",
        showLabel: true,
      },
      {
        id: "languages",
        label: "LANGUAGES",
        type: "language-list",
        required: false,
        x: 5.5,
        y: 63.5,
        width: 31.5,
        height: 8,
        fontSize: 9.4,
        color: "#111827",
        maxChars: 160,
        maxLines: 4,
        sourceKey: "languages",
        showLabel: true,
        defaultEnabled: true,
      },
      {
        id: "skills",
        label: "Skills",
        type: "list",
        required: true,
        x: 5.5,
        y: 76.6,
        width: 32,
        height: 18,
        fontSize: 9.8,
        color: "#111827",
        maxChars: 260,
        maxLines: 11,
        aiMode: "fit-template-space",
        sourceKey: "skills",
        showLabel: true,
      },
      {
        id: "about",
        label: "ABOUT ME",
        type: "textarea",
        required: true,
        x: 47.8,
        y: 12.1,
        width: 43.8,
        height: 18.2,
        fontSize: 7.6,
        fontWeight: "semibold",
        color: "#20242a",
        align: "justify",
        maxChars: 780,
        maxLines: 10,
        aiMode: "improve-summary",
        sourceKey: "about",
        showLabel: true,
      },
      {
        id: "workExperience",
        label: "WORK EXPERIENCE",
        type: "experience-list",
        required: true,
        x: 47.8,
        y: 35.0,
        width: 42.5,
        height: 18.6,
        fontSize: 7.2,
        color: "#111827",
        maxChars: 860,
        maxLines: 14,
        aiMode: "ats",
        sourceKey: "workExperience",
        showLabel: true,
      },
      {
        id: "expertise",
        label: "EXPERTISE",
        type: "textarea",
        required: false,
        x: 47.8,
        y: 61.0,
        width: 43,
        height: 16.8,
        fontSize: 7.8,
        color: "#20242a",
        align: "justify",
        maxChars: 670,
        maxLines: 11,
        aiMode: "professional",
        sourceKey: "expertise",
        showLabel: true,
      },
      {
        id: "deployments",
        label: "DEPLOYMENT",
        type: "project-list",
        required: false,
        x: 47.8,
        y: 81.2,
        width: 28.5,
        height: 13.2,
        fontSize: 6.8,
        color: "#0b2239",
        maxChars: 430,
        maxLines: 8,
        aiMode: "project-description",
        sourceKey: "deployments",
        showLabel: true,
      },
      {
        id: "portfolioUrl",
        label: "Portfolio URL",
        type: "link",
        required: false,
        x: 75.6,
        y: 80.7,
        width: 19.5,
        height: 2.4,
        fontSize: 6.5,
        fontWeight: "semibold",
        color: "#0f5f9f",
        maxChars: 48,
        maxLines: 1,
        sourceKey: "portfolioUrl",
        linkType: "portfolio",
      },
      {
        id: "qr",
        label: "QR source URL",
        type: "qr",
        required: false,
        x: 79.6,
        y: 84.2,
        width: 12.7,
        height: 9.4,
        fontSize: 7,
        color: "#111827",
        sourceKey: "qr",
        linkType: "custom",
      },
      {
        id: "githubUrl",
        label: "GitHub URL",
        type: "link",
        required: false,
        x: 47.8,
        y: 96.0,
        width: 22.5,
        height: 1.8,
        fontSize: 6.2,
        color: "#0f5f9f",
        maxChars: 54,
        maxLines: 1,
        sourceKey: "githubUrl",
        linkType: "github",
      },
      {
        id: "linkedinUrl",
        label: "LinkedIn URL",
        type: "link",
        required: false,
        x: 71.6,
        y: 96.0,
        width: 22.5,
        height: 1.8,
        fontSize: 6.2,
        color: "#0f5f9f",
        maxChars: 54,
        maxLines: 1,
        sourceKey: "linkedinUrl",
        linkType: "linkedin",
      },
    ],
  },
];

export function getCanvaResumeTemplate(templateId: string) {
  return canvaResumeTemplates.find((template) => template.id === templateId);
}

export function isCanvaResumeTemplate(templateId: string) {
  return Boolean(getCanvaResumeTemplate(templateId));
}
