import type { CanvaResumeTemplate } from "@/types/template";

// How to add more Canva templates:
// 1. Design the resume as A4 in Canva.
// 2. Export it as PNG.
// 3. Put the PNG in public/templates.
// 4. Add a template object to this registry.
// 5. Adjust each field's x/y/width/height percentage values until the overlay fits.
//
// Coordinates are percentage-based from 0 to 100. The live preview uses the same
// values directly, and the PDF renderer converts them into A4 points.

export const canvaResumeTemplates: CanvaResumeTemplate[] = [
  {
    id: "my-cv",
    name: "My CV Visual Template",
    description: "One-page visual CV based on the Canva design.",
    thumbnail: "/templates/My-CV.png",
    backgroundImage: "/templates/My-CV.png",
    pageSize: "A4",
    coordinateSystem: {
      unit: "percent",
      width: 100,
      height: 100,
    },
    fields: [
      {
        id: "profileImage",
        label: "Profile image",
        type: "image",
        required: false,
        x: 7.5,
        y: 6.2,
        width: 21,
        height: 15,
        fontSize: 10,
        color: "#111827",
        sourceKey: "profileImage",
      },
      {
        id: "fullName",
        label: "Full name",
        type: "text",
        required: true,
        x: 34,
        y: 7,
        width: 54,
        height: 5,
        fontSize: 22,
        fontWeight: "bold",
        color: "#111827",
        maxChars: 34,
        maxLines: 1,
        aiMode: "fit-template-space",
        sourceKey: "fullName",
      },
      {
        id: "jobTitle",
        label: "Job title",
        type: "text",
        required: true,
        x: 34,
        y: 12.6,
        width: 49,
        height: 3,
        fontSize: 10,
        fontWeight: "semibold",
        color: "#2f5f8f",
        maxChars: 42,
        maxLines: 1,
        sourceKey: "jobTitle",
      },
      {
        id: "phone",
        label: "Phone",
        type: "phone",
        required: true,
        x: 9,
        y: 25.4,
        width: 24,
        height: 2.5,
        fontSize: 8,
        color: "#111827",
        maxChars: 22,
        maxLines: 1,
        sourceKey: "phone",
        linkType: "phone",
      },
      {
        id: "email",
        label: "Email",
        type: "email",
        required: true,
        x: 9,
        y: 28.6,
        width: 27,
        height: 2.5,
        fontSize: 8,
        color: "#111827",
        maxChars: 34,
        maxLines: 1,
        sourceKey: "email",
        linkType: "email",
      },
      {
        id: "location",
        label: "Location",
        type: "text",
        required: false,
        x: 9,
        y: 31.8,
        width: 26,
        height: 2.5,
        fontSize: 8,
        color: "#111827",
        maxChars: 34,
        maxLines: 1,
        sourceKey: "location",
      },
      {
        id: "about",
        label: "About me",
        type: "textarea",
        required: true,
        x: 38,
        y: 19.2,
        width: 52,
        height: 12,
        fontSize: 8.2,
        color: "#243447",
        align: "justify",
        maxChars: 430,
        maxLines: 8,
        aiMode: "improve-summary",
        sourceKey: "about",
      },
      {
        id: "workExperience",
        label: "Work experience",
        type: "experience-list",
        required: true,
        x: 38,
        y: 36,
        width: 51,
        height: 14,
        fontSize: 7.5,
        color: "#111827",
        maxChars: 620,
        maxLines: 11,
        aiMode: "ats",
        sourceKey: "workExperience",
      },
      {
        id: "developerExperience",
        label: "Developer experience",
        type: "textarea",
        required: false,
        x: 38,
        y: 52.5,
        width: 51,
        height: 8,
        fontSize: 7.5,
        color: "#111827",
        maxChars: 330,
        maxLines: 6,
        aiMode: "professional",
        sourceKey: "developerExperience",
      },
      {
        id: "education",
        label: "Education",
        type: "education-list",
        required: true,
        x: 38,
        y: 63.7,
        width: 51,
        height: 8,
        fontSize: 7.4,
        color: "#111827",
        maxChars: 300,
        maxLines: 5,
        sourceKey: "education",
      },
      {
        id: "expertise",
        label: "Expertise",
        type: "list",
        required: false,
        x: 8,
        y: 41,
        width: 24,
        height: 8,
        fontSize: 7.8,
        color: "#111827",
        maxChars: 180,
        maxLines: 6,
        sourceKey: "expertise",
      },
      {
        id: "skills",
        label: "Skills",
        type: "list",
        required: true,
        x: 8,
        y: 52.8,
        width: 24,
        height: 11,
        fontSize: 7.8,
        color: "#111827",
        maxChars: 240,
        maxLines: 8,
        sourceKey: "skills",
      },
      {
        id: "languages",
        label: "Languages",
        type: "language-list",
        required: false,
        x: 8,
        y: 67,
        width: 24,
        height: 6,
        fontSize: 7.8,
        color: "#111827",
        maxChars: 120,
        maxLines: 4,
        sourceKey: "languages",
      },
      {
        id: "deployments",
        label: "Projects / deployments",
        type: "project-list",
        required: false,
        x: 38,
        y: 75.2,
        width: 51,
        height: 9,
        fontSize: 7.2,
        color: "#111827",
        maxChars: 390,
        maxLines: 7,
        aiMode: "project-description",
        sourceKey: "deployments",
      },
      {
        id: "portfolioUrl",
        label: "Portfolio URL",
        type: "link",
        required: false,
        x: 38,
        y: 88.8,
        width: 34,
        height: 2.5,
        fontSize: 7.4,
        color: "#0f5f9f",
        maxChars: 48,
        maxLines: 1,
        sourceKey: "portfolioUrl",
        linkType: "portfolio",
      },
      {
        id: "githubUrl",
        label: "GitHub URL",
        type: "link",
        required: false,
        x: 38,
        y: 91.7,
        width: 34,
        height: 2.5,
        fontSize: 7.4,
        color: "#0f5f9f",
        maxChars: 48,
        maxLines: 1,
        sourceKey: "githubUrl",
        linkType: "github",
      },
      {
        id: "linkedinUrl",
        label: "LinkedIn URL",
        type: "link",
        required: false,
        x: 38,
        y: 94.6,
        width: 34,
        height: 2.5,
        fontSize: 7.4,
        color: "#0f5f9f",
        maxChars: 48,
        maxLines: 1,
        sourceKey: "linkedinUrl",
        linkType: "linkedin",
      },
      {
        id: "qr",
        label: "QR source URL",
        type: "qr",
        required: false,
        x: 78,
        y: 87.5,
        width: 11,
        height: 8,
        fontSize: 7,
        color: "#111827",
        sourceKey: "qr",
        linkType: "custom",
      },
    ],
  },
];

export function getCanvaResumeTemplate(templateId: string) {
  return canvaResumeTemplates.find((template) => template.id === templateId);
}

export function isCanvaResumeTemplate(templateId: string) {
  return Boolean(getCanvaResumeTemplate(templateId));
}
